name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git clone git@github.com:retyui/react-native-confirmation-code-field.git
      - run: cd react-native-confirmation-code-field && yarn install --frozen-lockfile --ignore-engines && yarn test && yarn lint
        env:
          CI: true
